version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 667:667
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile-waitress
    ports:
      - 8080:8080
